<a href="https://colab.research.google.com/github/husnanzzry/FYP_Degree/blob/main/preprocessed_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('new_cleaned_dataset.csv')

In [ ]:
data.head()

,retweetCount,DateCreated,text_cleaned,Bank_Name
0,3,29/1/2023,it is best to use the maybank app the apps run...,Maybank
1,21,3/1/2023,doqtahu mymaybank this must have malicious app...,Maybank
2,0,18/1/2023,service bsn problem news is the daily light ma...,Maybank
3,0,9/1/2023,maybank apps statement be 1 green and 99 red,Maybank
4,0,16/1/2023,something wrong with maybank mae apps,Maybank

In [ ]:
import nltk
nltk.download('punkt')  # download the punkt tokenizer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
data['text_tokenized'] = data['text_cleaned'].apply(nltk.word_tokenize)

In [ ]:
data.head()

,retweetCount,DateCreated,text_cleaned,Bank_Name,text_tokenized
0,3,29/1/2023,it is best to use the maybank app the apps run...,Maybank,"[it, is, best, to, use, the, maybank, app, the..."
1,21,3/1/2023,doqtahu mymaybank this must have malicious app...,Maybank,"[doqtahu, mymaybank, this, must, have, malicio..."
2,0,18/1/2023,service bsn problem news is the daily light ma...,Maybank,"[service, bsn, problem, news, is, the, daily, ..."
3,0,9/1/2023,maybank apps statement be 1 green and 99 red,Maybank,"[maybank, apps, statement, be, 1, green, and, ..."
4,0,16/1/2023,something wrong with maybank mae apps,Maybank,"[something, wrong, with, maybank, mae, apps]"

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
stop_words = stopwords.words('english')

In [ ]:
def remove_stop_words(text):
  words = text.split()
  filtered_words = [word for word in words if word not in stop_words]
  return ' '.join(filtered_words)

In [ ]:
data['text_nostopwords'] = data['text_tokenized'].apply(lambda x: [word for word in x if word not in stop_words])

In [ ]:
data.head()

,retweetCount,DateCreated,text_cleaned,Bank_Name,text_tokenized,text_nostopwords
0,3,29/1/2023,it is best to use the maybank app the apps run...,Maybank,"[it, is, best, to, use, the, maybank, app, the...","[best, use, maybank, app, apps, run, smoothly,..."
1,21,3/1/2023,doqtahu mymaybank this must have malicious app...,Maybank,"[doqtahu, mymaybank, this, must, have, malicio...","[doqtahu, mymaybank, must, malicious, apps, ph..."
2,0,18/1/2023,service bsn problem news is the daily light ma...,Maybank,"[service, bsn, problem, news, is, the, daily, ...","[service, bsn, problem, news, daily, light, ma..."
3,0,9/1/2023,maybank apps statement be 1 green and 99 red,Maybank,"[maybank, apps, statement, be, 1, green, and, ...","[maybank, apps, statement, 1, green, 99, red]"
4,0,16/1/2023,something wrong with maybank mae apps,Maybank,"[something, wrong, with, maybank, mae, apps]","[something, wrong, maybank, mae, apps]"

In [ ]:
"""import nltk
nltk.download('wordnet')
data['text_lemmatized'] = data['text_nostopwords'].apply(lambda x: [nltk.wordnet.WordNetLemmatizer().lemmatize(word) for word in x])"""

"import nltk\nnltk.download('wordnet')\ndata['text_lemmatized'] = data['text_nostopwords'].apply(lambda x: [nltk.wordnet.WordNetLemmatizer().lemmatize(word) for word in x])"

In [ ]:
from nltk.stem import WordNetLemmatizer

# Download necessary resources
nltk.download('wordnet')

# Create WordNetLemmatizer instance
lemmatizer = WordNetLemmatizer()

# Define function to lemmatize tokens
def lemmatize(tokens):
    lemmatized_tokens = []
    for token in tokens:
        lemmatized_token = None
        for pos in ['n', 'v', 'a', 'r']:
            lemmatized_token = lemmatizer.lemmatize(token, pos=pos)
            if lemmatized_token != token:
                break
        lemmatized_tokens.append(lemmatized_token)
    return ' '.join(lemmatized_tokens)

# Apply lemmatization to the tokenized column
data['text_lemmatized'] = data['text_nostopwords'].apply(lemmatize)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
data.head(10)

,retweetCount,DateCreated,text_cleaned,Bank_Name,text_tokenized,text_nostopwords,text_lemmatized
0,3,29/1/2023,it is best to use the maybank app the apps run...,Maybank,"[it, is, best, to, use, the, maybank, app, the...","[best, use, maybank, app, apps, run, smoothly,...",best use maybank app apps run smoothly money m...
1,21,3/1/2023,doqtahu mymaybank this must have malicious app...,Maybank,"[doqtahu, mymaybank, this, must, have, malicio...","[doqtahu, mymaybank, must, malicious, apps, ph...",doqtahu mymaybank must malicious apps phone as...
2,0,18/1/2023,service bsn problem news is the daily light ma...,Maybank,"[service, bsn, problem, news, is, the, daily, ...","[service, bsn, problem, news, daily, light, ma...",service bsn problem news daily light make mybs...
3,0,9/1/2023,maybank apps statement be 1 green and 99 red,Maybank,"[maybank, apps, statement, be, 1, green, and, ...","[maybank, apps, statement, 1, green, 99, red]",maybank apps statement 1 green 99 red
4,0,16/1/2023,something wrong with maybank mae apps,Maybank,"[something, wrong, with, maybank, mae, apps]","[something, wrong, maybank, mae, apps]",something wrong maybank mae apps
5,1,27/1/2023,why are there even two apps in the first place...,Maybank,"[why, are, there, even, two, apps, in, the, fi...","[even, two, apps, first, place, maybank, maybank]",even two apps first place maybank maybank
6,0,30/1/2023,not me 122 am open maybank apps to check salar...,Maybank,"[not, me, 122, am, open, maybank, apps, to, ch...","[122, open, maybank, apps, check, salary, stil...",122 open maybank apps check salary still yet
7,0,29/1/2023,i hear money coming in from maybank apps but n...,Maybank,"[i, hear, money, coming, in, from, maybank, ap...","[hear, money, coming, maybank, apps, maybank]",hear money come maybank apps maybank
8,0,27/1/2023,every month maybank apps must make my blood ri...,Maybank,"[every, month, maybank, apps, must, make, my, ...","[every, month, maybank, apps, must, make, bloo...",every month maybank apps must make blood rise ...
9,19,2/1/2023,how to check asb dividend through mae apps 1 l...,Maybank,"[how, to, check, asb, dividend, through, mae, ...","[check, asb, dividend, mae, apps, 1, login, ma...",check asb dividend mae apps 1 login maybank ma...

In [ ]:
#from nltk.stem import PorterStemmer
#data['text_stemmed'] = data['text_lemmatized'].apply(lambda x: [PorterStemmer().stem(word) for word in x])

In [ ]:
#data.head(10)

In [ ]:
#data['text_preprocessed'] = data['text_lemmatized'].apply(lambda x: ' '.join(x))

In [ ]:
#data.head()

In [ ]:
df = pd.DataFrame(data)

# Save the dataframe to a CSV file
df.to_csv('preprocessed_dataset(3).csv', index=False)

In [ ]:
data = pd.read_csv('new_cleaned_dataset.csv')

In [ ]:
data.head()

,retweetCount,DateCreated,text_cleaned,Bank_Name
0,3,29/1/2023,it is best to use the maybank app the apps run...,Maybank
1,21,3/1/2023,doqtahu mymaybank this must have malicious app...,Maybank
2,0,18/1/2023,service bsn problem news is the daily light ma...,Maybank
3,0,9/1/2023,maybank apps statement be 1 green and 99 red,Maybank
4,0,16/1/2023,something wrong with maybank mae apps,Maybank